### ISSUE TITLE
More Sign Out Issues - Page Cacheing

### ISSUE THREAD

**Issue by mfouladi** [mfouladi/CollegeHotlineTest#14]
So right now if you are on the conversations page (or any page while signed in), then sign out of the system, and then click the back button in your browser, you are returned to the "signed in" page.

What this means is that you can click "sign out" again and since you are not signed in, it will return an error message as listed below.

What we want to happen is that when a person signs out, access should be restricted and all other sessions closed. So for example, if you have two windows open and you sign out of one, then the other window should go to a signed out page as well and not remain in the conversations or notes.

TypeError: Cannot read property '0' of undefined
   at app.post.passport.authenticate.successRedirect (/var/www/CollegeHotlineTest/CollegeHotline/server.js:103:44)
   at Layer.handle [as handle_request](/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/layer.js:82:5)
   at next (/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request](/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/layer.js:82:5)
   at /var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/index.js:234:24
   at Function.proto.process_params (/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/index.js:312:12)
   at /var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/index.js:228:12
   at Function.match_layer (/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/index.js:295:3)
   at next (/var/www/CollegeHotlineTest/CollegeHotline/node_modules/express/lib/router/index.js:189:10)

**Comment by mfouladi** [comment]
I think the best way to handle this is to require a database check when the user loads a page (onload function). If the user is logged in, then the page is loaded, otherwise the user is redirected.
